name: Functional Tests (zkEVM)
on:
  push:
    branches: [ main, DX-2552/port-zkevm-tests ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install root dependencies
      run: npm install -g yarn && yarn install --immutable

    - name: Build SDK
      run: yarn build

    - name: Install functional tests dependencies
      run: cd tests/func-tests/zkevm && yarn install --no-immutable

    - name: Run tests
      run: cd tests/func-tests/zkevm && yarn test:ci
