name: Functional Tests (zkEVM)
on:
  push:
    branches: [ main, DX-2552/port-zkevm-tests ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install root dependencies
      run: npm install -g yarn && yarn install --immutable

    - name: Build SDK
      run: yarn build

    - name: Install functional tests dependencies
      run: cd tests/func-tests/zkevm && yarn install --no-immutable

    - name: Run tests
      env:
        CHAIN_NAME: imtbl-zkevm-devnet
        API_URL: https://api.dev.immutable.com
        RPC_URL: https://rpc.dev.immutable.com
        TEST_ZKEVM_WALLET_BANKER_PRIVATE_KEY: ${{ secrets.TEST_ZKEVM_WALLET_BANKER_PRIVATE_KEY }}
        TEST_ZKEVM_WALLET_MNEMONIC: ${{ secrets.TEST_ZKEVM_WALLET_MNEMONIC }}
        TEST_ZKEVM_API_RATE_LIMIT_BYPASS_KEY: ${{ secrets.TEST_ZKEVM_API_RATE_LIMIT_BYPASS_KEY }}
        TEST_ZKEVM_PROJECT_HUB_GENERATED_API_KEY: ${{ secrets.TEST_ZKEVM_PROJECT_HUB_GENERATED_API_KEY }}
      run: cd tests/func-tests/zkevm && yarn test:ci
