name: Publish to NPM

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: Release Type
        options:
          - alpha
          - beta
          - release
          - release-candidate
        required: true
        default: alpha
      upgrade_type:
        type: choice
        description: Upgrade Type
        options:
          - ""
          - patch
          - minor
          - major
        required: true
        default: ""
      pre_release_revision:
        type: choice
        description: '(Optional) Pre release revision bump'
        required: false
        options:
          - ""
          - revision
        default: ""


jobs:
  Publish:
    name: Publish Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get tags
        run: git fetch --tags

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      # - name: Get yarn cache directory path
      #   id: yarn-cache-dir-path
      #   run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      # - name: Cache node modules
      #   uses: actions/cache@v3
      #   id: yarn-cache
      #   with:
      #     path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-

      # - name: Install dependencies
      #   run: yarn install --immutable

      # - name: Build
      #   run: yarn build

      # - name: Check Single Package Version Policy
      #   run: yarn syncpack:check

      # - name: Lint
      #   run: yarn lint

      # - name: Build
      #   run: yarn build

      # - name: Typecheck
      #   run: yarn typecheck

      # - name: Test
      #   run: yarn test

      - name: Update package.json version for pre (alpha, beta) releases
        if: ${{ contains(github.event.inputs.tag, 'alpha') || contains(github.event.inputs.tag, 'beta') || contains(github.event.inputs.tag, 'release-candidate') }}
        run: |
          tmp=$(mktemp)
          jq '.version = "${{github.event.inputs.tag}}"' ./sdk/package.json > "$tmp" && mv "$tmp" ./sdk/package.json
          
      - name: Get next version string
        id: version
        run: |
          echo "$(./.github/scripts/version-up.sh --${{github.event.inputs.release_type }} --${{ github.event.inputs.upgrade_type }} --apply --${{ github.event.inputs.pre_release_revision }})"
          echo "$(git push --tags)"
          echo "NEXT_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Print Next Version
        run: |
          echo "Next Version: ${{steps.version.outputs.NEXT_VERSION}}"
      #  Commenting out as this is still WIP

      - name: Pre Release Step
        if: ${{ contains(github.event.inputs.tag, 'alpha') || contains(github.event.inputs.tag, 'beta') }} || contains(github.event.inputs.tag, 'release-candidate') }}
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.PLATFORM_SA_NPM_TOKEN }}
          access: public
          package: ./sdk/package.json
          tag: ${{ steps.version.outputs.NEXT_VERSION }}
          dry-run: true

      - name: Print New Version
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.PLATFORM_SA_NPM_TOKEN }}
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"

      # - name: Authenticate NPM
      #   run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.PLATFORM_SA_NPM_TOKEN }}

      # - name: Release
      #   if: ${{ contains(github.event.inputs.release_type, 'patch') || contains(github.event.inputs.release_type, 'minor') || contains(github.event.inputs.release_type, 'major') }}
      #   run: yarn release ${{github.event.inputs.release_type}} --ci
